#! /usr/bin/env bash
echo "==delete bucket"

#Check for a bucket name
if [ -z "$1" ]; then
    echo "there needs to be a bucket name eg. ./bucket my-bucket-name."
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
  --bucket $BUCKET_NAME \
  --region us-east-1 \
  --query Location \
  --output text