#!/usr/bin/env bash

echo "==delete-objects"
# Exit immediately if any command returns a zero 
set -e

#Check for bucket name
if [ -z "$1" ]; then
    echo "there needs to be a bucket name eg. ./bucket my-bucket-name."
    exit 1
fi

BUCKET_NAME=$1  

aws s3api delete-objects --bucket $BUCKET_NAME