#!/usr/bin/env bash
echo "==put-object"

#Check for bucket name
if [ -z "$1" ]; then
    echo "there needs to be a bucket name eg. ./bucket my-bucket-name."
    exit 1
fi

#Check for file name 
if [ -z "$2" ]; then
    echo "there needs to be a file name  eg. ./bucket my-bucket-name my-file-name."
    exit 1
fi
BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME") 
aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY