#!/usr/bin/env bash

echo "==sync"
# Exit immediately if any command returns a zero 
set -e

#Check for bucket name
if [ -z "$1" ]; then
    echo "there needs to be a bucket name eg. ./bucket my-bucket-name."
    exit 1
fi

#Check for file name prefix
if [ -z "$2" ]; then
    echo "there needs to be a file name prefix eg. ./bucket my-bucket-name my-file-name-prefix."
    exit 1
fi
BUCKET_NAME=$1
FILENAME_PREFIX=$2
# where we'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove the folder if it already exists
rm -r $OUTPUT_DIR

# create output folder
mkdir -p $OUTPUT_DIR

# generate a random number 
# to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))
echo "Number of files to create: $NUM_FILES"

for ((i=1; i<=NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"
    echo "Creating file: $FILENAME"

    # Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 
done

# Verify the files
tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files